import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { Bell, BellOff, CheckCheck, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { keys } from '../../api/keys';
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Pagination, Segmented, SelectField, Skeleton } from '../../components/ui';
import { useCurrentUser } from '../../hooks/useAuth';
import { useApiMutation, usePageTitle } from '../../hooks/misc';
import { deleteNotification, listNotifications, markAllNotificationsRead, markNotificationRead } from '../../services/notifications';
import type { AppNotification, NotificationType } from '../../types';
import { cn } from '../../utils/cn';
import { NOTIFICATION_META } from '../../utils/constants';
import { timeAgo } from '../../utils/format';
import { resolveNotificationLink } from '../../utils/links';

type Scope = 'all' | 'unread';

export default function NotificationsPage() {
  usePageTitle('Notifications');
  const user = useCurrentUser();
  const navigate = useNavigate();
  const [scope, setScope] = useState<Scope>('all');
  const [type, setType] = useState<NotificationType | ''>('');
  const [page, setPage] = useState(1);

  const filters = { page, pageSize: 15, unread: scope === 'unread', type };
  const query = useQuery({ queryKey: keys.notifications(filters), queryFn: () => listNotifications(filters), placeholderData: keepPreviousData });

  const refresh = [keys.notificationsAll];
  const markRead = useApiMutation({ mutationFn: (id: string) => markNotificationRead(id), invalidate: refresh });
  const markAll = useApiMutation({ mutationFn: () => markAllNotificationsRead(), successMessage: (result) => `${result.updated} notification${result.updated === 1 ? '' : 's'} marked as read`, invalidate: refresh });
  const remove = useApiMutation({ mutationFn: (id: string) => deleteNotification(id), invalidate: refresh });

  const open = (notification: AppNotification) => {
    if (!notification.isRead) markRead.mutate(notification.id);
    const target = resolveNotificationLink(notification.link, user.role);
    if (target) navigate(target);
  };

  const unreadCount = query.data?.meta.unreadCount ?? 0;

  return (
    <div className="animate-fade-in">
      <PageHeader
        eyebrow="Account"
        title="Notifications"
        description="Deadlines, results, certificates, recommendations and announcements. Reminders are generated by the platform from your real progress."
        actions={
          <Button variant="secondary" disabled={unreadCount === 0} loading={markAll.isPending} onClick={() => markAll.mutate()} leftIcon={<CheckCheck size={16} />}>
            Mark all as read
          </Button>
        }
      />

      <div className="mb-5 flex flex-wrap items-end justify-between gap-4">
        <Segmented
          label="Show notifications"
          value={scope}
          onChange={(value) => {
            setScope(value);
            setPage(1);
          }}
          items={[
            { id: 'all', label: 'All' },
            { id: 'unread', label: `Unread${unreadCount ? ` (${unreadCount})` : ''}` },
          ]}
        />
        <SelectField
          label="Type"
          wrapperClassName="w-56"
          value={type}
          onChange={(event) => {
            setType(event.target.value as NotificationType | '');
            setPage(1);
          }}
        >
          <option value="">All types</option>
          {(Object.keys(NOTIFICATION_META) as NotificationType[]).map((key) => (
            <option key={key} value={key}>
              {NOTIFICATION_META[key].label}
            </option>
          ))}
        </SelectField>
      </div>

      {query.isLoading ? (
        <div className="space-y-3" role="status" aria-label="Loading notifications">
          {[0, 1, 2, 3].map((item) => (
            <Skeleton key={item} className="h-20 rounded-2xl" />
          ))}
        </div>
      ) : query.isError ? (
        <ErrorState error={query.error} onRetry={() => void query.refetch()} />
      ) : query.data && query.data.items.length === 0 ? (
        <EmptyState
          title={scope === 'unread' ? 'You are all caught up' : 'No notifications yet'}
          description={scope === 'unread' ? 'There is nothing unread.' : 'Notifications about your training will appear here.'}
          icon={scope === 'unread' ? <BellOff size={18} /> : <Bell size={18} />}
        />
      ) : query.data ? (
        <Card padded={false}>
          <ul className="divide-y divide-slate-100">
            {query.data.items.map((notification) => {
              const meta = NOTIFICATION_META[notification.type];
              const target = resolveNotificationLink(notification.link, user.role);
              return (
                <li key={notification.id} className={cn('flex items-start gap-4 px-5 py-4', !notification.isRead && 'bg-sky/[0.04]')}>
                  <span className={cn('mt-2 h-2.5 w-2.5 shrink-0 rounded-full', notification.isRead ? 'bg-transparent' : 'bg-sky')} aria-hidden />
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={meta.tone}>{meta.label}</Badge>
                      <span className="text-xs text-slate-500">{timeAgo(notification.createdAt)}</span>
                      {!notification.isRead && <span className="sr-only">Unread</span>}
                    </div>
                    <p className={cn('mt-1.5 text-sm text-navy', notification.isRead ? 'font-semibold' : 'font-bold')}>{notification.title}</p>
                    <p className="mt-0.5 text-sm leading-6 text-slate-500">{notification.message}</p>
                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      {target && (
                        <Button size="sm" variant="light" onClick={() => open(notification)}>
                          Open
                        </Button>
                      )}
                      {!notification.isRead && (
                        <Button size="sm" variant="ghost" onClick={() => markRead.mutate(notification.id)}>
                          Mark as read
                        </Button>
                      )}
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => remove.mutate(notification.id)}
                    aria-label={`Delete notification: ${notification.title}`}
                    className="rounded-lg p-2 text-slate-300 transition hover:bg-red-50 hover:text-red-500"
                  >
                    <Trash2 size={16} />
                  </button>
                </li>
              );
            })}
          </ul>
          <Pagination meta={query.data.meta} onPage={setPage} label="Notification pages" />
        </Card>
      ) : null}
    </div>
  );
}
