/** Central query-key factory so invalidation after a mutation is precise and typo-proof. */
export const keys = {
  me: ['me'] as const,
  options: ['meta', 'options'] as const,

  // learner
  dashboardTrainee: ['dashboard', 'trainee'] as const,
  passport: ['passport'] as const,
  competenciesMe: ['competencies', 'me'] as const,
  skillGaps: ['skill-gaps'] as const,
  skillGapsAt: (offsetDays: number) => ['skill-gaps', offsetDays] as const,
  recommendations: ['recommendations'] as const,
  myEnrollments: (status?: string) => ['enrollments', 'me', status ?? 'active'] as const,
  enrollmentsAll: ['enrollments'] as const,
  learn: (courseId: string) => ['learn', courseId] as const,
  myAssessments: ['assessments', 'me'] as const,
  assessmentInfo: (id: string) => ['assessments', id, 'info'] as const,
  attempt: (id: string) => ['assessments', 'attempt', id] as const,
  assessmentResults: (id: string, filters?: unknown) => ['assessments', id, 'results', filters ?? {}] as const,
  certificates: ['certificates', 'me'] as const,
  achievements: ['achievements'] as const,
  evaluationsMe: ['evaluations', 'me'] as const,

  // catalog
  courses: (filters?: unknown) => ['courses', 'list', filters ?? {}] as const,
  coursesAll: ['courses'] as const,
  course: (id: string) => ['courses', 'detail', id] as const,
  courseFeedback: (id: string, page?: number) => ['courses', id, 'feedback', page ?? 1] as const,
  competencies: (filters?: unknown) => ['competencies', 'list', filters ?? {}] as const,
  competenciesAll: ['competencies'] as const,
  competency: (id: string) => ['competencies', 'detail', id] as const,

  // trainer
  dashboardTrainer: ['dashboard', 'trainer'] as const,
  managedAssessments: (courseId?: string) => ['assessments', 'managed', courseId ?? 'all'] as const,
  managedAssessment: (id: string) => ['assessments', id, 'managed'] as const,
  courseTrainees: (id: string, filters?: unknown) => ['courses', id, 'trainees', filters ?? {}] as const,
  courseAnalytics: (id: string) => ['courses', id, 'analytics'] as const,
  evaluations: (filters?: unknown) => ['evaluations', 'list', filters ?? {}] as const,
  rubric: ['evaluations', 'rubric'] as const,
  employeePassport: (id: string) => ['passport', id] as const,

  // admin
  adminAnalytics: (months: number) => ['admin', 'analytics', months] as const,
  adminAnalyticsAll: ['admin', 'analytics'] as const,
  heatmap: (filters: unknown) => ['admin', 'heatmap', filters] as const,
  heatmapCell: (filters: unknown) => ['admin', 'heatmap-cell', filters] as const,
  trainingNeeds: (filters: unknown) => ['admin', 'training-needs', filters] as const,
  trainingNeed: (id: string, filters: unknown) => ['admin', 'training-need', id, filters] as const,
  skillGapAnalytics: (filters: unknown) => ['admin', 'skill-gaps', filters] as const,
  forecast: (horizon: number) => ['admin', 'forecast', horizon] as const,
  users: (filters: unknown) => ['admin', 'users', filters] as const,
  usersAll: ['admin', 'users'] as const,
  userDetail: (id: string) => ['admin', 'users', 'detail', id] as const,
  departments: (all?: boolean) => ['departments', all ? 'all' : 'active'] as const,
  roles: (all?: boolean) => ['roles', 'list', all ? 'all' : 'active'] as const,
  rolesAll: ['roles'] as const,
  role: (id: string) => ['roles', 'detail', id] as const,
  certificatesAdmin: (filters: unknown) => ['admin', 'certificates', filters] as const,
  certificatesAdminAll: ['admin', 'certificates'] as const,
  announcementsAdmin: (page: number) => ['admin', 'announcements', page] as const,
  announcementsAdminAll: ['admin', 'announcements'] as const,
  announcements: ['announcements'] as const,
  auditLogs: (filters: unknown) => ['admin', 'audit-logs', filters] as const,
  engineConfig: ['admin', 'engine-config'] as const,

  // operational readiness (the offset is part of the key so each simulated date caches separately)
  readinessOverview: (offsetDays: number) => ['readiness', 'overview', offsetDays] as const,
  readinessCalendar: (offsetDays: number) => ['readiness', 'calendar', offsetDays] as const,
  eventReadiness: (eventId: string, offsetDays: number) => ['readiness', 'event', eventId, offsetDays] as const,
  succession: (offsetDays: number) => ['succession', offsetDays] as const,
  successionDetail: (competencyId: string, offsetDays: number) => ['succession', 'competency', competencyId, offsetDays] as const,
  myMentorships: ['succession', 'mentorships', 'me'] as const,
  readinessEvents: (filters?: unknown) => ['readiness', 'events', filters ?? {}] as const,
  readinessEventsAll: ['readiness'] as const,
  readinessEvent: (eventId: string) => ['readiness', 'event', 'detail', eventId] as const,
  eventAssignments: (eventId: string) => ['readiness', 'event', eventId, 'assignments'] as const,
  myReadinessAssignments: ['readiness', 'assignments', 'me'] as const,

  // AR Instrument Lab
  arModules: (offsetDays: number) => ['ar', 'modules', offsetDays] as const,
  arModulesAll: ['ar'] as const,
  arModule: (idOrKey: string) => ['ar', 'module', idOrKey] as const,
  arAttempt: (attemptId: string) => ['ar', 'attempt', attemptId] as const,
  arRefresher: (offsetDays: number) => ['ar', 'refresher', offsetDays] as const,
  arAttempts: (filters?: unknown) => ['ar', 'attempts', filters ?? {}] as const,
  arAnalytics: ['ar', 'analytics'] as const,

  // shared
  notifications: (filters?: unknown) => ['notifications', 'list', filters ?? {}] as const,
  notificationsAll: ['notifications'] as const,
  unreadCount: ['notifications', 'unread'] as const,
  profile: ['profile'] as const,
  search: (q: string) => ['search', q] as const,
  verify: (id: string) => ['verify', id] as const,
};
