import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import type { StorageProvider, StoredFileStream } from './types';

/** Keys are generated by the server, but validate anyway: no traversal, no absolute paths. */
const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9/_.-]*$/;

/** Development storage on the local file system. */
export class LocalStorageProvider implements StorageProvider {
  readonly driver = 'local' as const;
  private readonly root: string;

  constructor(directory: string) {
    this.root = path.resolve(directory);
  }

  /** Absolute path of a key (validated). Lets the API use `res.sendFile`, which supports HTTP Range requests for video seeking. */
  absolutePath(key: string): string {
    return this.resolveKey(key);
  }

  private resolveKey(key: string): string {
    if (!SAFE_KEY.test(key) || key.includes('..')) throw new Error(`Invalid storage key: ${key}`);
    const target = path.resolve(this.root, key);
    if (!target.startsWith(this.root + path.sep)) throw new Error('Storage key escapes the storage root');
    return target;
  }

  async put(key: string, body: Buffer, _contentType?: string): Promise<void> {
    const target = this.resolveKey(key);
    await fsp.mkdir(path.dirname(target), { recursive: true });
    await fsp.writeFile(target, body);
  }

  async getStream(key: string): Promise<StoredFileStream> {
    const target = this.resolveKey(key);
    const stats = await fsp.stat(target);
    return { stream: fs.createReadStream(target), size: stats.size };
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fsp.access(this.resolveKey(key));
      return true;
    } catch {
      return false;
    }
  }

  async delete(key: string): Promise<void> {
    await fsp.rm(this.resolveKey(key), { force: true });
  }
}
